# Generated by Django 4.1.2 on 2023-01-04 03:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='کد تخفیف')),
                ('valid_from', models.DateTimeField(verbose_name='زمان شروع')),
                ('valid_to', models.DateTimeField(verbose_name='زمان پایان')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخیف')),
                ('discount_limit', models.IntegerField(blank=True, null=True, verbose_name='حداکثر مقدار تخفیف')),
                ('active', models.BooleanField(default=False, verbose_name='فعال است')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره پیگیری')),
                ('status', models.CharField(choices=[('درحال آماده سازی', 'درحال آماده سازی'), ('ارسال شده', 'ارسال شده'), ('تحویل داده شده', 'تحویل داده شده'), ('لغو شده', 'لغو شده'), ('مرجوع شده', 'مرجوع شده')], default='درحال آماده سازی', max_length=50, verbose_name='وضعیت سفارش')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discount', models.IntegerField(blank=True, default=None, null=True, verbose_name='درصد تخفیف')),
                ('discount_limit', models.IntegerField(blank=True, default=None, null=True, verbose_name='حداکثر مقدار تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ('-paid', '-updated'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color', verbose_name='رنگ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('state', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.CharField(max_length=512, verbose_name='نشانی پستی')),
                ('tag', models.IntegerField(verbose_name='پلاک')),
                ('unit', models.IntegerField(blank=True, null=True, verbose_name='واحد')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='orders.order')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
    ]
