# Generated by Django 4.1.2 on 2023-01-20 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderaddress',
            options={'verbose_name': 'گیرنده', 'verbose_name_plural': 'گیرنده ها'},
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='شماره پیگیری'),
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=255, verbose_name='مبلغ تراکنش')),
                ('pay_ref', models.CharField(max_length=255, verbose_name='شماره پیگیری تراکنش(مستند)')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='orders.order')),
            ],
        ),
    ]
