# Generated by Django 4.1.2 on 2023-03-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderaddress_options_alter_order_ref_id_pay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay',
            options={'verbose_name': 'اطلاعات پرداخت', 'verbose_name_plural': 'اطلاعات پرداخت'},
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='کد سفارش'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='pay_ref',
            field=models.CharField(max_length=255, verbose_name='شماره پیگیری (مستند)'),
        ),
    ]
