# Generated by Django 4.1.2 on 2022-12-27 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_alter_coupon_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-paid', '-updated'), 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='sent',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('درحال آماده سازی', 'درحال آماده سازی'), ('ارسال شده', 'ارسال شده'), ('تحویل داده شده', 'تحویل داده شده'), ('لغو شده', 'لغو شده'), ('مرجوع شده', 'مرجوع شده')], default='درحال آماده سازی', max_length=50, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره پیگیری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
