# Generated by Django 4.1.2 on 2022-12-07 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_orderitem_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=512)),
                ('tag', models.IntegerField()),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('postal_code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_address', to='orders.order')),
            ],
        ),
    ]
