# Generated by Django 4.1.2 on 2022-12-07 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_postaladdress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_limit', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='address',
            field=models.CharField(max_length=512, verbose_name='نشانی پستی'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='city',
            field=models.CharField(max_length=255, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='state',
            field=models.CharField(max_length=255, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='tag',
            field=models.IntegerField(verbose_name='پلاک'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='unit',
            field=models.IntegerField(blank=True, null=True, verbose_name='واحد'),
        ),
    ]
