# Generated by Django 4.1.2 on 2022-11-20 20:10

import ckeditor.fields
import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('cover', models.ImageField(upload_to='brands/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('grade', models.CharField(choices=[('n', 'New'), ('o', 'Openbox'), ('s', 'Stoke')], max_length=1)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cover', models.ImageField(upload_to='products/cover/%Y/%m/%d')),
                ('available', models.BooleanField(default=True)),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand')),
                ('category', models.ManyToManyField(related_name='products', to='products.category')),
                ('color', models.ManyToManyField(to='products.color')),
                ('images', models.ManyToManyField(to='products.image')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=1)),
                ('size', models.CharField(max_length=255)),
                ('cpu_maker', models.CharField(max_length=255)),
                ('cpu_model', models.CharField(max_length=255)),
                ('cpu_cache', models.PositiveIntegerField(null=True)),
                ('cpu_description', models.TextField(blank=True, null=True)),
                ('has_gpu', models.BooleanField(default=False)),
                ('gpu_model', models.CharField(blank=True, max_length=255, null=True)),
                ('gpu_memory', models.PositiveIntegerField(blank=True, null=True)),
                ('gpu_description', models.TextField(blank=True, null=True)),
                ('ram_capacity', models.PositiveIntegerField()),
                ('ram_type', models.CharField(max_length=255)),
                ('ram_description', models.TextField(blank=True, null=True)),
                ('has_hdd', models.BooleanField(default=False)),
                ('hdd_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('has_ssd', models.BooleanField(default=False)),
                ('ssd_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('hard_description', models.TextField(blank=True, null=True)),
                ('screen_size', models.DecimalField(decimal_places=1, max_digits=1)),
                ('screen_type', models.CharField(max_length=255)),
                ('screen_resolution', models.CharField(max_length=255)),
                ('screen_matte', models.BooleanField(default=False)),
                ('screen_touch', models.BooleanField(default=False)),
                ('screen_description', models.TextField(blank=True, null=True)),
                ('optical_drive', models.BooleanField(default=False)),
                ('webcam', models.CharField(max_length=255)),
                ('touchpad_specs', models.CharField(max_length=255)),
                ('keyboard_backlight', models.CharField(max_length=255)),
                ('card_reader', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('bluetooth', models.CharField(max_length=255)),
                ('ethernet', models.BooleanField(default=False)),
                ('vga', models.BooleanField(default=False)),
                ('hdmi', models.BooleanField(default=False)),
                ('usb2_num', models.PositiveIntegerField(blank=True, null=True)),
                ('usb3_num', models.PositiveIntegerField(blank=True, null=True)),
                ('type_c', models.BooleanField(default=False)),
                ('thunderbolt', models.BooleanField(default=False)),
                ('cat', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('include_items', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.product')),
            ],
        ),
    ]
