# Generated by Django 4.1.2 on 2023-01-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='available',
            field=models.BooleanField(default=False, verbose_name='این رنگ از محصول موجود است'),
        ),
    ]
