# Generated by Django 4.1.2 on 2022-11-30 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='cpu_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_series', to='products.cpuseries'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='gpu_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_makers', to='products.gpumaker'),
        ),
    ]
