# Generated by Django 4.1.2 on 2022-12-26 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_compare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compare',
            options={'verbose_name': 'مقایسه', 'verbose_name_plural': 'مقایسه ها'},
        ),
        migrations.AlterField(
            model_name='compare',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='compare',
            name='session_key',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='سشن'),
        ),
        migrations.AlterField(
            model_name='compare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
