# Generated by Django 4.1.2 on 2022-12-04 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_color_available_alter_color_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد موجودی این رنگ'),
        ),
    ]
