# Generated by Django 4.1.2 on 2022-12-01 00:18

import ckeditor.fields
import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_has_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlehit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='articlehit',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ipaddress', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='articlehit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='cover',
            field=models.ImageField(upload_to='brands', verbose_name='عکس کاور'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.comment', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cpuseries',
            name='series',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='gpumaker',
            name='maker',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='products/images/%Y/%m/%d', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='آدرس IP'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='products.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='products.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(upload_to='products/cover/%Y/%m/%d', verbose_name='عکس کاور'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='grade',
            field=models.CharField(choices=[('n', 'آکبند'), ('o', 'اپن باکس'), ('s', 'استوک')], max_length=1, verbose_name='گرید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='products.ArticleHit', to='products.ipaddress', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='battery',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='bluetooth',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='cpu_description',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='cpu_maker',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='cpu_model',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='cpu_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_series', to='products.cpuseries', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='ethernet',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='fingerprint',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='gpu_description',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='gpu_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_makers', to='products.gpumaker', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='gpu_memory',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='gpu_model',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='hard_description',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='has_gpu',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='has_hdd',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='has_ssd',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='hdd_capacity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='hdmi',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='include_items',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='jack_3',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='keyboard_backlight',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='name',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='optical_drive',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='os',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.product', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='ram_capacity',
            field=models.PositiveIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='ram_description',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='ram_type',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='screen_description',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='screen_matte',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='screen_resolution',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='screen_size',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='screen_touch',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='screen_type',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='sd_card',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='size',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='ssd_capacity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='thunderbolt',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='touchpad_specs',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='type_c',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='usb2_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='usb3_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='vga',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='webcam',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='specification',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
